//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX, quindi eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IZWebFileManagerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IZWebFileManagerResource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IZWebFileManagerResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte
        ///   le ricerche di risorse che utilizzano questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Arrange Icons By.
        /// </summary>
        internal static string Arrange_Icons_By {
            get {
                return ResourceManager.GetString("Arrange_Icons_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot Complete Operation..
        /// </summary>
        internal static string CannotCompleteOperation {
            get {
                return ResourceManager.GetString("CannotCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot find file, Make sure the path is correct..
        /// </summary>
        internal static string CannotFindFile {
            get {
                return ResourceManager.GetString("CannotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot rename file: A file with the name you specified already exists. Specify a different file name..
        /// </summary>
        internal static string CannotRenameFile {
            get {
                return ResourceManager.GetString("CannotRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Folder.
        /// </summary>
        internal static string Create_New_Folder {
            get {
                return ResourceManager.GetString("Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date Modified.
        /// </summary>
        internal static string Date_Modified {
            get {
                return ResourceManager.GetString("Date_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete selected items?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The destination folder is a subfolder of the source folder..
        /// </summary>
        internal static string DestinationFolderIsSubfolder {
            get {
                return ResourceManager.GetString("DestinationFolderIsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File Folder.
        /// </summary>
        internal static string File_Folder {
            get {
                return ResourceManager.GetString("File_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Folder Path.
        /// </summary>
        internal static string Folder_Path {
            get {
                return ResourceManager.GetString("Folder_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Icons.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient user privileges to complete the operation.
        /// </summary>
        internal static string Insufficient_privileges {
            get {
                return ResourceManager.GetString("Insufficient_privileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You must type a file name..
        /// </summary>
        internal static string MustTypeFileName {
            get {
                return ResourceManager.GetString("MustTypeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Folder.
        /// </summary>
        internal static string New_Folder {
            get {
                return ResourceManager.GetString("New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Folder.
        /// </summary>
        internal static string New_Folder_Name {
            get {
                return ResourceManager.GetString("New_Folder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A file name cannot contain any of the following characters: \/:*?&quot;&lt;&gt;|.
        /// </summary>
        internal static string NotAllowedCharacters {
            get {
                return ResourceManager.GetString("NotAllowedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DoubleClick to open a folder. DoubleClick to download a file..
        /// </summary>
        internal static string No_Command_Help {
            get {
                return ResourceManager.GetString("No_Command_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Files.
        /// </summary>
        internal static string Root_File {
            get {
                return ResourceManager.GetString("Root_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Flash Movies.
        /// </summary>
        internal static string Root_Flash {
            get {
                return ResourceManager.GetString("Root_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Images.
        /// </summary>
        internal static string Root_Image {
            get {
                return ResourceManager.GetString("Root_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Media.
        /// </summary>
        internal static string Root_Media {
            get {
                return ResourceManager.GetString("Root_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        internal static string SearchWatermark {
            get {
                return ResourceManager.GetString("SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select destination directory.
        /// </summary>
        internal static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Thumbnails.
        /// </summary>
        internal static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload Another File.
        /// </summary>
        internal static string Upload_Another_File {
            get {
                return ResourceManager.GetString("Upload_Another_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Or drag &apos;nd drop one or more files on the above area.
        /// </summary>
        internal static string Upload_dnd {
            get {
                return ResourceManager.GetString("Upload_dnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File exceeds maximum size allowed ({0} mb).
        /// </summary>
        internal static string Upload_Error_1 {
            get {
                return ResourceManager.GetString("Upload_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File type not allowed or not supported..
        /// </summary>
        internal static string Upload_Error_2 {
            get {
                return ResourceManager.GetString("Upload_Error_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User does not have sufficient privileges..
        /// </summary>
        internal static string Upload_Error_3 {
            get {
                return ResourceManager.GetString("Upload_Error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upload File.
        /// </summary>
        internal static string Upload_File {
            get {
                return ResourceManager.GetString("Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Click here to upload a file.
        /// </summary>
        internal static string Upload_File_click {
            get {
                return ResourceManager.GetString("Upload_File_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove.
        /// </summary>
        internal static string Upload_File_Remove {
            get {
                return ResourceManager.GetString("Upload_File_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File type not allowed or not supported..
        /// </summary>
        internal static string Upload_not_allowed {
            get {
                return ResourceManager.GetString("Upload_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File &quot;{0}&quot; was successfully uploaded.
        /// </summary>
        internal static string Upload_success {
            get {
                return ResourceManager.GetString("Upload_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File view.
        /// </summary>
        internal static string View_file {
            get {
                return ResourceManager.GetString("View_file", resourceCulture);
            }
        }
    }
}
